# Utiliser une image de base Node.js
FROM node:18

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et installer les dépendances
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

# Copier le reste des fichiers du frontend
COPY frontend ./

# Exposer le port du frontend
EXPOSE 3000

# Lancer le frontend
CMD ["npm", "start"]
